### ISSUE TITLE
Benchmark js-libp2p transfer performance

### ISSUE THREAD

**Issue by p-shahi** [libp2p/test-plans#65] opened 2022-10-20 23:48 UTC
- [ ] Add [js-libp2p-transfer-performance](https://github.com/ipfs-shipyard/js-libp2p-transfer-performance) as a test in this repo and CI job to benchmark transfer times across releases to catch issues like [#1342](https://github.com/libp2p/js-libp2p/issues/1342)

**Comment by mxinden** [comment] 2023-06-28 05:18
To make sure we are on the same page:

> as a test-plan

We no-longer plan to write a Testground test-plan, correct?

> Add [js-libp2p-transfer-performance](https://github.com/ipfs-shipyard/js-libp2p-transfer-performance) as a test-plan and CI job to benchmark transfer times across releases to catch issues like https://github.com/libp2p/js-libp2p/issues/1342

- One would add the `js-libp2p` `perf` implementation implemented in https://github.com/libp2p/js-libp2p/pull/1604 to https://github.com/libp2p/test-plans/tree/master/perf/impl. See guide in https://github.com/libp2p/test-plans/tree/master/perf#adding-a-new-implementation.
- One would either trigger the [`perf` GitHub workflow](https://github.com/libp2p/test-plans/blob/master/.github/workflows/perf.yml) from a pull request on libp2p/test-plans before every release, or trigger the workflow on every pull request on libp2p/js-libp2p.
- Based on the results reported by the workflow, more specifically the updated [`benchmark-results.json`](https://raw.githubusercontent.com/libp2p/test-plans/master/perf/runner/benchmark-results.json) one can e.g. fail the CI run due to 20% performance regression.

Is this accurate @p-shahi and @maschad?

**Comment by maschad** [comment] 2023-06-28 15:58
> One would add the js-libp2p perf implementation implemented in https://github.com/libp2p/js-libp2p/pull/1604 to [master/perf/impl](https://github.com/libp2p/test-plans/tree/master/perf/impl?rgh-link-date=2023-06-28T05%3A18%3A37Z). See guide in [master/perf#adding-a-new-implementation](https://github.com/libp2p/test-plans/tree/master/perf?rgh-link-date=2023-06-28T05%3A18%3A37Z#adding-a-new-implementation).

This seems accurate although I think the format of the _Output_  as mentioned in the [guide](https://github.com/libp2p/test-plans/tree/master/perf#adding-a-new-implementation) would need to be modified to accommodate the scenario that https://github.com/libp2p/js-libp2p/pull/1604 seeks to address specifically i.e. [gauging single connection throughput](https://github.com/libp2p/specs/blob/master/perf/perf.md#single-connection-throughput) by measuring how many bytes were transferred by the total time it took from stream open to stream close. So my understanding is that would exclude the time taken to _establish the connection_.


> One would either trigger the [perf GitHub workflow](https://github.com/libp2p/test-plans/blob/master/.github/workflows/perf.yml?rgh-link-date=2023-06-28T05%3A18%3A37Z) from a pull request on libp2p/test-plans before every release, or trigger the workflow on every pull request on libp2p/js-libp2p.

👍🏾 


> Based on the results reported by the workflow, more specifically the updated [benchmark-results.json](https://raw.githubusercontent.com/libp2p/test-plans/master/perf/runner/benchmark-results.json) one can e.g. fail the CI run due to 20% performance regression.

Agreed, although looking at the current [benchmark-results.json](https://raw.githubusercontent.com/libp2p/test-plans/master/perf/runner/benchmark-results.json) though there doesn't seem to be a format for running in different environments (such as browser vs webworkers vs node) but I don't suppose the _Output format_ stipulated in https://github.com/libp2p/test-plans/tree/master/perf#adding-a-new-implementation prevents that based on my interpretation, so there would need to be some changes to the format `benchmark-results.json`

**Comment by justin0mcateer** [comment] 2023-07-28 15:24
> We no-longer plan to write a Testground test-plan, correct?

I was planning to use Testground for a similar purpose. I see that there was some work committed recently to enable browser environments there. Is there some reason using Testground is undesirable or wouldn't achieve the desired outcome?

**Comment by maschad** [comment] 2023-07-28 15:38
> > We no-longer plan to write a Testground test-plan, correct?
> 
> We have been planning to use Testground for a similar purpose. I see that there was some work committed recently to enable browser environments there. Is there some reason using Testground is undesirable or wouldn't achieve the desired outcome?

In the first use case which was to start up two nodes and have them ping each other, we found Testground was too complicated and slow for what we wanted to do, you can read more about that [here](https://github.com/libp2p/test-plans/issues/103)

**Comment by achingbrain** [comment] 2023-11-21 17:10
This was (re)enabled by #325 so this can probably be closed now?

**Closed** 2023-11-21 21:11 UTC
